package com.example.pyracalendar.database

import com.google.firebase.database.IgnoreExtraProperties

@IgnoreExtraProperties
data class Veranstaltung(
    val user: String? = null,
    val status: String? = null,
    val kunde: String? = null,
    val personen: Int? = null,
    val vaArt: String? = null,
    val vaZeitraum: String? = null,
    val raum: String? = null,
    val raumTV: String? = null,
    val raumAV: String? = null,
    val erstellDatum: String? = null,
    val blockDatum: String? = null,
    val mehrtaegig: Boolean? = null,
    val aufbautage: Boolean? = null,
    val aufbauBeginn: String? = null,
    val abbauEnde: String? = null,
    val datumBeginn: String? = null,
    val datumEnde: String? = null,
    val zeitBeginn: String? = null,
    val zeitEnde: String? = null,
    val zeitBeginnTV: String? = null,
    val zeitEndeTV: String? = null,
    val zeitBeginnAV: String? = null,
    val zeitEndeAV: String? = null,
    val kontakt: String? = null,
    val mail: String? = null,
    val telefon: String? = null,
    val beschreibung: String? = null,
    val budgetierung: Boolean? = null,
    val bestuhlplan: Boolean? = null,
    val vertrag: Boolean? = null,
    val rechn1gestellt: Boolean? = null,
    val rechn1bezahlt: Boolean? = null,
    val rechn2gestellt: Boolean? = null,
    val rechn2bezahlt: Boolean? = null,
    val rechn3gestellt: Boolean? = null,
    val rechn3bezahlt: Boolean? = null,
    val sortierung: Long? = null,
)